### PR TITLE
Remove colons from filename

### PR DESCRIPTION
**Pull request by bmagic007**
This patch makes the resulting file more compatible with remote filesystems.

### CODE REVIEW

**Comment by berick** [comment]
Thanks, Blake.  Any chance this could be handled with a command line option?  We have some notice types which are generated many times an hour, so they contain time stamps, e.g. checkout-locker-email-2021-10-09T13:48:00.xml.  I'd like to retain the ":" in those file names.  (They have not been a problem for us).

**Comment by berick** [comment]
Hm, or maybe just replace ":" with "_" so they are still readable.

**Comment by bmagic007** [comment]
The colons are still retained in the END_DATE variable, which is required for some date math code elsewhere. This patch should address the filename only. Replacing the colon with an underscore seems fine too. Would you like me to make this an option? If so, it would have implications down the stack of scripts. Probably a new environment variable. As opposed to hard coding it to remove the colons from the filename. I feel that removing the colons from the filename is a good idea to make the resulting filename more compatible in general and it should just do that without making the user provide the switch.

**Comment by bmagic007** [comment]
Unique is migrating to a new SCP server. I think* it's a Window server, which is the catalyst for this patch.

**Comment by berick** [comment]
Interesting... OK, I'm good w/ scrubbing the colons.  Thanks for talking it through.

**Pull request merged**
